[global]
       workgroup = WORKGROUP
       server string = Home Server
       netbios name = homeserver
       security = user
       map to guest = Bad User
       server min protocol = SMB2

[SOFT]
       path = /mnt/media/soft/
       browseable = yes
       read only = yes
       guest ok = yes
       public = yes
       force user = smbuser
[FILMS]
       path = /mnt/media/films
       browseable = yes
       read only = yes
       guest ok = yes
       public = yes
       force user = smbuser

[DISTR]
       path = /mnt/media/distr
       browseable = yes
       read only = yes
       guest ok = yes
       public = yes
       force user = smbuser

[MUSIC]
       path = /mnt/media/music
       browseable = yes
       read only = no
       valid users = smbuser
       force user = smbuser
       create mask = 0664
       directory mask = 0775
